files:
  - source: /res/values/alpha_strings.xml
    translation: /res/values-%android_code%/%original_file_name%
  - source: /res/values/cr_strings.xml
    translation: /res/values-%android_code%/%original_file_name%
